services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.15.2
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - ~/imx-frigate-main/frigate-config:/config
      #- /usr/bin/ffmpeg:/usr/bin/ffmpeg
      #- /usr/bin/ffprobe:/usr/bin/ffprobe
      #- /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      #- "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      #- "8554:8554" # RTSP feeds
      #- "8555:8555/tcp" # WebRTC over tcp
      #- "8555:8555/udp" # WebRTC over udp
    networks:
      - frigate
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token <YOUR_TUNNEL_TOKEN>
    networks:
      - frigate

networks:
  frigate: